language: python

python:
  - "3.4"

services:
  - postgresql

addons:
  postgresql: "9.3"

env:
  - DATABASE_URL=postgres://postgres@localhost/test

install:
  - pip install tox
  - pip install codecov

before_script:
  - psql -c 'create database test;' -U postgres
  - mkdir -p shippable/codecoverage
  - mkdir -p shippable/testresults

script: tox

after_success:
  - mv coverage.xml shippable/codecoverage
